#!/usr/bin/env python

import yaml, sys

if __name__ == '__main__':
    with open(sys.argv[1], 'r') as fh:
        data = yaml.load(fh)

    if len(sys.argv)>2:
        with open(sys.argv[2], 'w') as fh:
            yaml.dump(data, stream=fh, default_flow_style=False, allow_unicode=True, width=2048)
    else:
        print( yaml.dump(data, default_flow_style=False, allow_unicode=True, width=2048) )

